src/webtools/appsearcher/urls.py
from django.urls import path

from appsearcher.views import AppSearchView

app_name = 'appsearcher'

urlpatterns = [
    path('', AppSearchView.as_view(), name='search_app'),
]

src/webtools/core/urls.py
from django.urls import path

from core.views import IndexView

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

src/webtools/keywordfinder/urls.py
from django.urls import path

from keywordfinder.views import KeywordFindView

app_name = 'keywordfinder'

urlpatterns = [
    path('', KeywordFindView.as_view(), name='find_keyword'),
]

src/webtools/webtools/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('searchapp/', include('appsearcher.urls')),
    path('findkeyword/', include('keywordfinder.urls')),
]

src/webtools/core/models.py
from django.db import models

# Create your models here.

src/webtools/core/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

src/webtools/core/templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %} | WebTools</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS v4.5.0 -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Custom CSS -->
    {% block css %}{% endblock %}
</head>
<body>
<div class="container">
    <!-- Header -->
    <ul class="nav row my-2">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'core:index' %}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'appsearcher:search_app' %}">App Searcher</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'keywordfinder:find_keyword' %}">Keywords Finder</a>
        </li>
    </ul>
    <!-- END Header -->

    <!-- Content -->
    <div class="page-content">
        {% block content %}{% endblock %}
    </div>
    <!-- END Content -->
</div>

<!-- jQuery v3.1.0 -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap Bundle v4.5.0 -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>
<!-- Custom JavaScript -->
{% block javascript %}{% endblock %}
</body>
</html>

src/webtools/core/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}WebTools{% endblock %}

{% block css %}
    <style>
        blockquote {
            border-left: .25em solid #e0e3e6;
            color: #6a737d;
            padding: 0 1em;
        }
    </style>
{% endblock %}

{% block content %}
    <h1 class="h4 mb-4">App Searcher and Keywords Finder</h1>

    <h2 class="h5 mb-3">About</h2>
    <blockquote class="mb-4">
        App searcher module is used to get information about apps on the Google Play Store and Apple App Store.<br>
        Keyword searcher module is used to get all the keywords from the currently given url and show the recommended
        url and keywords from the existing url.
    </blockquote>

    <h2 class="h5">Built With</h2>
    <ul>
        <li><a href="https://www.python.org/" target="_blank">Python</a> is a powerful general-purpose programming
            language. It is used in web development, data science, creating software prototypes, and so on. Fortunately
            for beginners, Python has simple easy-to-use syntax. This makes Python an excellent language to learn to
            program for beginners.
        </li>
        <li><a href="https://www.djangoproject.com/" target="_blank">Django</a> is a free and open source high-level Web
            framework that encourages rapid development and clean, pragmatic design.
        </li>
        <li><a href="https://getbootstrap.com/" target="_blank">Bootstrap</a> Quickly design and customize responsive
            mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass
            variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript
            plugins.
        </li>
        <li><a href="https://jquery.com/" target="_blank">jQuery</a> is a fast, small, and feature-rich JavaScript
            library. It makes things like HTML document traversal and manipulation, event handling, animation, and Ajax
            much simpler with an easy-to-use API that works across a multitude of browsers.
        </li>
    </ul>
{% endblock %}